FROM node:22-alpine

WORKDIR /app

# для нативних модулів (bcrypt / sharp / etc.)
RUN apk add --no-cache python3 make g++ libc6-compat

# ставимо deps з lock-файлом (в тебе він є)
COPY package.json package-lock.json ./
RUN npm ci

# копіюємо все (потрібно для первинного запуску; далі буде volume)
COPY . .

# Nest CLI глобально НЕ треба — будемо запускати через npx
CMD ["node", "-e", "console.log('Set command in docker-compose')"]
