FROM node:25-alpine AS builder

WORKDIR /var/www

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build:all


# ---------- PROD ----------
FROM node:25-alpine

WORKDIR /var/www

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /var/www/dist ./dist

# НІЯКОГО DEFAULT ENTRYPOINT
CMD ["node", "dist/apps/authorization/main.js"]
