name: 'Build and Deploy to Prod'

on:
  push:
    branches:
      - main

permissions: write-all

env:
  CONFLUENCE_USER: yaroslavberkuta@gmail.com
  CONFLUENCE_API_TOKEN: ATATT3xFfGF0dfpMCdiwslwH3rtzWth--mjROO8E6Ef89aL5LY83w1sUSW-h-25rdouIHOK8P5n2AZjWOsc6KrS5MqOfs9u66i73xhxYQx3ehvW-YcykkgEBGH6HjTSHqoeLdnb0gJhMb7r_HdBCcn1KPCmf_WoEuT_IIAjqiMX136N3_WE1eiY=D67E78CC

jobs:
  task-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Отримуємо всі коміти, які потрапили в поточну гілку
      - name: Get commit messages
        id: commits
        run: |
          git fetch --prune
          branch_name="${GITHUB_REF#refs/heads/}"
          commits=$(git log --pretty=format:"%s" origin/$branch_name..HEAD)
          echo "commits=$commits" >> $GITHUB_ENV


      # Витягування ключів задач з повідомлень комітів
      - name: Extract task keys from commit messages
        id: extract_keys
        run: |
          keys=$(echo "${{ env.commits }}" | grep -oE '\[([A-Za-z]+-[0-9]+)\]' | sort | uniq)
          echo "task_keys=$keys" >> $GITHUB_ENV

      # Формуємо звіт для Confluence
      - name: Create Confluence report
        run: |
          report="### Deploy Report\n\n**Version**: ${{ steps.version.outputs.version }}\n\n**Tasks in this build**: ${{ env.task_keys }}"

          curl --location 'https://fanscrm.atlassian.net//wiki/api/v2/pages' \
          --header 'Content-Type: application/json' \
          --header 'Accept: application/json' \
          --header 'Authorization: Basic eWFyb3NsYXZiZXJrdXRhQGdtYWlsLmNvbTpBVEFUVDN4RmZHRjAzMTJncWFfVThrUENDRjIwdG5yc3N2UHRWdGhSRlhqWDBsRjlSVXNndEdRMGxET1NFTkc3UVBZWC1MMHNkQXdBWmRTbVlrS2ZjU3lzamNwNUQxdVB5TkpqVWJKUmd4eXNua09rLWpaVmFEekZpNGlNZ1EyVnVES2JqU2ZFdXRjbWc0RnNJWUZVeWQyakxUY3d6WHpIU3NqUW0zQmFuNzdrMzVjTmQ3T2lsZDA9MzgzOTJGREM=' \
          --header 'Cookie: atlassian.xsrf.token=e21e1cec2bf977a6a34ba2ea92fff3c6a1edfb30_lin' \
          --data '{
              "spaceId": "1802243",
              "status": "current",
              "title": "Build Report for Version ${{ steps.version.outputs.version }}",
              "parentId": "420642853",
              "body": {
                  "representation": "storage",
                  "value": "'"$report"'",
              }
          }'
